name: Main

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build project
        run: |
          CC=clang
          CFLAGS="-Wall -Wextra -O2"
          LDFLAGS="-framework Foundation"
          SRC="main.m BrightnessControl.m KeyboardManager.m"
          OUT="mac-brightnessctl"
          $CC $CFLAGS $LDFLAGS -o $OUT $SRC
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
